apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: postgres
        image: order-db:latest
        imagePullPolicy: Never
        env:
          - name: POSTGRES_DB
            value: order_db
          - name: POSTGRES_USER
            value: order_db_user
          - name: POSTGRES_PASSWORD
            value: order
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  selector:
    app: order-db
  ports:
  - port: 5432
