apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z account-db 5432; do echo waiting for account-db; sleep 2; done; echo db ready']
      containers:
      - name: account
        image: 394291652146.dkr.ecr.us-east-1.amazonaws.com/account:v1.0.0
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: postgres://account_db_user:account@account-db:5432/account_db?sslmode=disable
        ports:
        - containerPort: 8080

